name: pset2
version: "1.0.0"
config-version: 2
profile: pset2

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

flags:
  send_anonymous_usage_stats: false

models:
  pset2:
    staging:
      +schema: SILVER
      +materialized: view
    silver:
      +schema: SILVER
      +materialized: table
    gold:
      +schema: GOLD
      +materialized: table
